### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Goran58** [dragino/openwrt_lede-18.06#2]
When I run **set_up_build_environment.sh** after initial clone I get a lot of following errors and the build fails: 

```
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..HEAD
fatal: Invalid revision range ee53a240ac902dc83209008a2671e7fdcf55957a..78c813bb416876091b3f1e8c826d2822fda42d85
```

Probably something is corrupt in the repository

**Comment by Goran58** [comment]
A workaround is to change the hardcoded revision in openwrt/scripts/getver.sh to a valid revision e,g:
`
#REBOOT=ee53a240ac902dc83209008a2671e7fdcf55957a
REBOOT=78c813bb416876091b3f1e8c826d2822fda42d85
`

**Comment by dragino** [comment]
Confirm to work. Thanks.
